version: 2
jobs:
  build:
    working_directory: /go/src/github.com/isindir/sops-secrets-operator
    docker:
      - image: isindir/sdk:latest
    steps:
      #- restore-cache:
      #    keys:
      #      - source-{{ .Branch }}-{{ .Revision }}
      #      - source-{{ .Branch }}-
      #      - source-
      - checkout
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - restore-cache:
          keys:
            - modules-{{ .Branch }}-{{ checksum "go.sum" }}
            - modules-{{ .Branch }}-
            - modules-
      #- save_cache:
      #    key: source-{{ .Branch }}-{{ .Revision }}
      #    paths:
      #      - "."
      - run:
          name: Fetch Go dependencies
          command: |
            make mod
      - save_cache:
          key: modules-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"
      - run:
          name: Run Tests
          command: |
            make test


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
