version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: sops-secrets-operator
          command: |
            echo "Placeholder for CI/CD pipeline"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
